<?php
$root = dirname(__DIR__);
$core = file_get_contents($root . '/includes/core/class-plugin.php');
$updater = file_get_contents($root . '/includes/core/class-updater.php');
$payments = file_get_contents($root . '/includes/modules/payments/class-module.php');
$adoptables = file_get_contents($root . '/includes/modules/adoptables/class-module.php');
$forms = file_get_contents($root . '/includes/modules/forms/class-module.php');
$proxy = file_get_contents($root . '/includes/modules/asm-proxy/class-module.php');
$js = file_get_contents($root . '/assets/js/admin-sortable.js');
$errors = [];
function ok($cond, $msg){ global $errors; if (!$cond) $errors[] = $msg; }
ok(substr_count($core, "'slug'=>'plugin-ui-suite'") === 1, 'Expected one suite settings admin registration.');
ok(strpos($core, "add_submenu_page('options-general.php','Rescue Plugin Suite Updates'") === false, 'Updates submenu must not be registered.');
ok(strpos($core, "add_submenu_page('options-general.php','Payments:") === false, 'Payments submenus must not be registered.');
ok(strpos($core, "'data-source'=>'Integrations'") !== false, 'Integrations tab missing.');
ok(strpos($core, "'registry'=>'Registry'") !== false && strpos($core, 'developer_mode_enabled') !== false, 'Registry tab must remain developer-only.');
ok(strpos($core, "'updates'=>'Updates'") !== false, 'Updates tab missing.');
ok(strpos($core, "'layout'=>'Layout builder','adopted'") === false, 'Standalone layout tab still registered.');
ok(strpos($updater, "const REPO = 'JayS67/Rescue-Plugin-Suite'") !== false, 'Canonical repository constant missing or wrong.');
ok(strpos($updater, 'JordanSutton/Rescue-Plugin-Suite') === false, 'Old hard-coded repository remains.');
ok(strpos($payments, "'payments_section'=>\$tab_id") !== false, 'Payments subtab URLs must stay inside suite page.');
ok(strpos($core, "plugin-ui-suite-payments-") !== false && strpos($core, 'redirect_legacy_admin_urls') !== false, 'Legacy payment redirects missing.');
ok(strpos($js, 'data-sortable-input') !== false && strpos($js, "join('\\n')") !== false, 'Sortable hidden field sync missing.');
ok(strpos($js, "ArrowUp") !== false && strpos($js, "ArrowDown") !== false, 'Keyboard reorder support missing.');
ok(strpos($adoptables, "rest_url('plugin/v1/adoptables')") !== false, 'Adoptables REST URL must be generated by WordPress for subdirectory installs.');
ok(strpos($adoptables, 'function setLoading(isLoading)') !== false && strpos($adoptables, '} finally {') !== false, 'Adoptables loading state must be cleared on both success and failure.');
ok(strpos($adoptables, 'Unable to load adoptable animals. Please try again later.') !== false, 'Adoptables failure path must replace the loading grid.');
ok(strpos($core, "name=\"suite[proxy][account]\"") !== false, 'ASM account control must be available in Integrations.');
ok(strpos($core, "name=\"suite[proxy][password]\"") !== false, 'ASM password control must be available in Integrations.');
ok(strpos($core, 'Configuration precedence') !== false, 'ASM Integration must explain configuration precedence.');
ok(strpos($proxy, 'function plugin_asm_configuration()') !== false, 'ASM must have one canonical configuration resolver.');
ok(strpos($proxy, 'function plugin_asm_online_form_url') !== false, 'ASM forms must use the canonical ASM URL builder.');
ok(strpos($forms, 'plugin_asm_online_form_url($form_id)') !== false, 'Standalone Forms must use the canonical ASM URL builder.');
ok(strpos($adoptables, 'plugin_asm_online_form_url($apply_form_id)') !== false, 'Adoptables Forms must use the canonical ASM URL builder.');
ok(strpos($forms, 'https://service.sheltermanager.com/asmservice') === false, 'Standalone Forms must not hard-code an ASM service URL.');
ok(strpos($adoptables, 'https://service.sheltermanager.com/asmservice') === false, 'Adoptables must not hard-code an ASM service URL.');
if ($errors) { fwrite(STDERR, implode("\n", $errors) . "\n"); exit(1); }
echo "Static admin IA checks passed\n";
